### PR TITLE
Freemius Insights integration.

### PR DESCRIPTION
**Pull request by fs-contributor**
On activation on a new site (not an update), the user will be automatically forwarded to the opt-in screen: 
image

Once he opt-in or skip, the temporary top-level menu item will dissapear, and the user will be redirected into the widgets.php page.

For users who've been using the plugin before and update to the Freemius powered version, they will get a new admin notice that looks like that:
image

It will continue to show till they opt-in or skip.

### CODE REVIEW

**Comment by borkweb** [comment]
This looks great! Thank you for Pull Requesting the integration :+1:

**Comment by peterchester** [comment]
One thing I'm not in love with here is the word "need". We don't need users
to approve this. We'd like their help.

I'm worried that this will alienate people. Do we have control over that
messaging?

**Comment by fs-contributor** [comment]
Yep, there's a filter to do that. You can add the following code right after the init function:
```
function iw_fs_custom_message( $default_message ) {
	$current_user = wp_get_current_user();
	$site_url          = get_site_url();

	$first_name = $current_user->user_firstname;
	if ( empty( $first_name ) ) {
		$first_name = $current_user->nickname;
	}

	return sprintf(
		__fs( 'hey-x' ) . '<br>' .
		__( 'In order to enjoy all our features and functionality, %s needs to connect your user, %s at %s, to %s' ),
		$first_name,
		'<b>' . iw_fs()->get_plugin_name() . '</b>',
		'<b>' . $current_user->user_login . '</b>',
		'<a href="' . $site_url . '" target="_blank">' . $site_url . '</a>',
		'<a href="https://freemius.com/wordpress/insights/" target="_blank">freemius.com</a>'
	);
}

iw_fs()->add_filter( 'connect_message', 'iw_fs_custom_message' );
```

**Comment by peterchester** [comment]
@borkweb, you mind working with @zbtirrell to come up with a softer phrasing so that we are asking our users for help instead of demanding something from them?

Thanks!

**Pull request merged**
